import type { Language, SiteContent } from './types'

export const content: Record<Language, SiteContent> = {
  fr: {
    brand: 'Impérial Digitale',
    location: 'Yaoundé, Cameroun',
    availability: 'Sur rendez-vous, en présentiel ou à distance',
    nav: {
      home: 'Accueil',
      about: 'À propos',
      services: 'Services',
      industries: 'Secteurs',
      approach: 'Notre approche',
      projects: 'Projets',
      contact: 'Contact',
    },
    meta: 'Impérial Digitale est un cabinet de conseil au Cameroun spécialisé en communication stratégique, transformation digitale, systèmes d’information, cybersécurité, conformité ISO et accompagnement des projets à impact.',
    hero: {
      eyebrow: 'Conseil · Technologie · Impact',
      title: 'Impérial Digitale',
      description: 'Cabinet de conseil en transformation digitale, systèmes d’information et communication stratégique.',
      slides: [
        { label: 'Une vision qui prend forme', alt: 'Tours de bureaux vitrées à la tombée du jour.' },
        { label: 'Ouvrir de nouvelles perspectives', alt: 'Façade vitrée d’un immeuble de bureaux éclairé la nuit.' },
        { label: 'Des fondations pour demain', alt: 'Infrastructure numérique avec des baies de serveurs dans un centre de données.' },
      ],
    },
    home: {
      introLabel: 'Donner du sens à la transformation',
      introTitle: 'Relier votre vision à une transformation concrète.',
      introBody: 'Nous accompagnons les organisations dans la digitalisation et l’automatisation de leurs opérations, la mise en place de systèmes d’information performants, la création et l’optimisation d’applications métiers et le déploiement de solutions technologiques stratégiques.',
      context: [
        'Les institutions africaines et les entreprises du continent regorgent d’un potentiel considérable. Pourtant, les processus manuels, le manque d’intégration des systèmes et la gestion fragmentée de l’information peuvent encore freiner leur développement.',
        'Impérial Digitale relie stratégie, communication, technologie et exécution pour renforcer la performance, améliorer la prise de décision et accélérer la transformation des organisations.',
        'Nous accompagnons les institutions publiques, les entreprises privées, les PME et PMI, les collectivités et les projets à impact dans la modernisation de leurs opérations et la structuration de leur image.',
      ],
      benefitsTitle: 'Des ambitions, des effets concrets attendus.',
      benefits: [
        'Une image plus forte et plus cohérente',
        'Des processus plus fluides et mieux pilotés',
        'Des outils digitaux adaptés aux besoins réels',
        'Une meilleure maîtrise des risques et de la sécurité',
        'Des équipes renforcées et mieux préparées au changement',
        'Des projets plus visibles, crédibles et finançables',
      ],
      whyTitle: 'Une vision globale. Une exécution rigoureuse.',
      why: [
        { title: 'Vision stratégique', body: 'Nous concevons des solutions alignées sur vos enjeux de positionnement, de performance et de croissance. Chaque outil s’inscrit dans une ambition claire.' },
        { title: 'Exécution rigoureuse', body: 'Nous vous accompagnons du diagnostic jusqu’au déploiement, avec une approche structurée, opérationnelle et orientée résultats.' },
        { title: 'Expertise transversale', body: 'Communication, branding, digital, systèmes d’information, cybersécurité, conformité et projets : nous connectons plusieurs expertises au service d’une même ambition.' },
        { title: 'Ancrage local, standards internationaux', body: 'Nous comprenons les réalités africaines tout en intégrant les exigences de qualité, de gouvernance et de performance attendues à l’international.' },
      ],
      closingTitle: 'Donnez une nouvelle dimension à votre organisation.',
      closingBody: 'De votre image à vos systèmes d’information, construisons des solutions adaptées à votre secteur, à vos enjeux et à vos ambitions.',
    },
    about: {
      eyebrow: 'Le cabinet',
      title: 'L’expertise au service de votre ambition.',
      intro: [
        'Impérial Digitale est un cabinet de conseil et d’exécution qui aide les organisations à relever les défis de la visibilité, de la gouvernance, de la performance et de la transformation numérique.',
        'Notre approche combine stratégie, technologie, image de marque, communication institutionnelle, innovation, conformité et accompagnement opérationnel.',
        'Nous croyons que la transformation ne se limite pas aux outils : elle repose sur une vision claire, des processus structurés, une marque forte et une capacité réelle à exécuter.',
      ],
      teamTitle: 'Des regards complémentaires, une ambition commune.',
      teamBody: [
        'Impérial Digitale s’appuie sur une équipe multidisciplinaire composée de spécialistes en transformation digitale, communication stratégique, systèmes d’information et gestion de projets.',
        'Nous réunissons des profils complémentaires capables de concevoir, piloter et déployer des solutions adaptées aux enjeux des institutions, des entreprises et des projets à impact.',
      ],
      founderName: 'Lara Loe',
      founderRole: 'Fondatrice & Directrice',
      founderBio: [
        'Ingénieure en systèmes d’information et cheffe de projets, Lara Loe possède une expertise dans la transformation digitale, la modernisation des processus et la structuration de solutions technologiques pour les organisations publiques et privées.',
        'Elle accompagne les institutions et les entreprises dans la mise en place de systèmes d’information, la digitalisation des opérations et la conduite de projets numériques à fort impact.',
        'À travers Impérial Digitale, elle porte la vision d’un cabinet capable d’aider les organisations africaines à atteindre des standards internationaux de performance, de gouvernance et d’innovation.',
      ],
      valuesTitle: 'Ce qui guide chaque mission.',
      values: [
        'Une approche à la fois stratégique, technique et opérationnelle',
        'Une expertise combinant communication, digital, systèmes d’information et conformité',
        'Des solutions adaptées aux institutions publiques, entreprises privées et projets à impact',
        'Une vision orientée résultats, gouvernance et durabilité',
      ],
    },
    servicesIntro: {
      eyebrow: 'Nos pôles d’expertise',
      title: 'De la stratégie à la mise en œuvre.',
      description: 'Cinq expertises complémentaires pour renforcer votre image, moderniser vos opérations et déployer des solutions utiles, sécurisées et durables.',
    },
    services: [
      {
        id: 'strategic-communication',
        title: 'Communication stratégique & image de marque',
        body: 'Nous concevons des stratégies de communication fortes pour aider les organisations à affirmer leur positionnement, renforcer leur crédibilité et protéger leur image.',
        items: [
          'Stratégie de communication interne et externe',
          'Création d’identité visuelle : logos, chartes graphiques, slogans',
          'Branding, storytelling et positionnement de marque',
          'Relations presse et communication institutionnelle',
          'Communication de crise',
          'Organisation d’événements professionnels et publics',
        ],
      },
      {
        id: 'digital-communication',
        title: 'Communication digitale & gestion d’image',
        body: 'Nous aidons les marques, dirigeants et institutions à développer une présence digitale cohérente, visible et maîtrisée.',
        items: [
          'Stratégie digitale et ligne éditoriale',
          'Community management et animation des réseaux sociaux',
          'Création de contenus : visuels, vidéos, textes, reels',
          'Personal branding pour dirigeants et experts',
          'Gestion de l’e-réputation',
          'Stratégie de réponse et communication en cas de crise digitale',
        ],
      },
      {
        id: 'digital-transformation',
        title: 'Transformation digitale & systèmes d’information',
        body: 'Nous accompagnons les organisations dans l’audit, la conception, le déploiement et la sécurisation de leurs systèmes numériques.',
        items: [
          'Audit digital et diagnostic de maturité numérique',
          'Cartographie des processus et réingénierie métier',
          'Développement de sites web, plateformes et applications métiers',
          'Conception et développement d’applications métiers sur mesure',
          'Optimisation, modernisation et amélioration des performances d’applications existantes',
          'Intégration ERP, CRM, GED et outils collaboratifs',
          'Assistance à maîtrise d’ouvrage, cadrage et déploiement de projets numériques',
          'Cybersécurité, plan de continuité d’activité et site de secours',
          'Mise en place d’infrastructures réseau : LAN, VPN, fibre, routeurs',
          'Téléphonie IP et standard virtuel',
          'Fourniture et installation de solutions internet professionnelles sécurisées',
        ],
      },
      {
        id: 'training-compliance',
        title: 'Formations, conformité & accompagnement',
        body: 'Nous renforçons les capacités des équipes et accompagnons les structures dans la mise en conformité et l’amélioration continue.',
        items: [
          'Formations en outils digitaux, bureautique, cybersécurité, réseaux et intelligence artificielle',
          'Coaching digital pour cadres, dirigeants et collectivités',
          'Élaboration de manuels de procédures, guides de gouvernance et protocoles',
          'Accompagnement à la mise en conformité aux normes ISO 9001, ISO 27001 et ISO 14001',
          'Sensibilisation à la culture numérique et à la gouvernance éthique',
          'Accompagnement à la certification, à l’évaluation et à l’audit externe',
        ],
      },
      {
        id: 'impact-projects',
        title: 'Appui aux entreprises & projets à impact',
        body: 'Nous aidons les entreprises, entrepreneurs et institutions à structurer leurs initiatives, sécuriser leur croissance et développer des projets à forte valeur sociale ou économique.',
        items: [
          'Accompagnement à la création ou transformation de PME et PMI',
          'Conseil en business model, branding, visibilité et digitalisation',
          'Appui au financement : dossiers, levée de fonds, subventions et partenariats public-privé',
          'Études de faisabilité et plans de développement',
          'Conception de plateformes digitales pour l’éducation, la santé, l’entrepreneuriat et les projets sociaux',
          'Gestion de projets à impact : smart city, mobilité, inclusion numérique et innovation territoriale',
        ],
      },
    ],
    industriesIntro: {
      eyebrow: 'Secteurs accompagnés',
      title: 'Vos réalités donnent le cap.',
      description: 'Chaque organisation a ses priorités, ses contraintes et son rythme. Nous adaptons notre accompagnement aux réalités de votre secteur, en Afrique et à l’international.',
    },
    industries: [
      { id: 'public-institutions', title: 'Institutions publiques & collectivités', body: 'Moderniser les services, structurer l’information et renforcer la communication institutionnelle au service d’une gouvernance plus efficace.', serviceIds: ['digital-transformation', 'strategic-communication', 'training-compliance'] },
      { id: 'private-companies', title: 'Entreprises privées & groupes en transformation', body: 'Aligner image, systèmes d’information et processus pour accompagner les évolutions de l’organisation et mieux piloter son développement.', serviceIds: ['digital-transformation', 'strategic-communication', 'training-compliance'] },
      { id: 'smes', title: 'PME & PMI', body: 'Structurer les opérations, renforcer la visibilité et choisir des outils digitaux adaptés aux besoins et aux moyens de l’entreprise.', serviceIds: ['impact-projects', 'digital-transformation', 'digital-communication'] },
      { id: 'health-social', title: 'Santé & projets sociaux', body: 'Concevoir des plateformes utiles, organiser les processus et accompagner des initiatives dont la valeur se mesure au service rendu aux personnes.', serviceIds: ['impact-projects', 'digital-transformation', 'training-compliance'] },
      { id: 'education', title: 'Éducation & formation', body: 'Développer les compétences, accompagner les usages numériques et concevoir des dispositifs digitaux au service de l’apprentissage.', serviceIds: ['training-compliance', 'digital-transformation', 'impact-projects'] },
      { id: 'mobility', title: 'Logistique, mobilité & smart city', body: 'Cadrer les projets territoriaux, relier les systèmes et exploiter les outils numériques pour faciliter la coordination et la prise de décision.', serviceIds: ['impact-projects', 'digital-transformation', 'strategic-communication'] },
      { id: 'media', title: 'Médias, communication & marques personnelles', body: 'Clarifier le positionnement, construire une présence digitale cohérente et accompagner les dirigeants dans la maîtrise de leur image.', serviceIds: ['strategic-communication', 'digital-communication'] },
    ],
    approachIntro: {
      eyebrow: 'Notre approche',
      title: 'Une méthode claire, à chaque étape.',
      description: 'Du premier échange à l’amélioration continue, chaque mission est conçue dans une logique de pérennité, de transfert de compétences, de gouvernance et d’impact mesurable.',
    },
    steps: [
      { title: 'Diagnostic & écoute des besoins', body: 'Comprendre votre organisation, vos objectifs et les difficultés rencontrées sur le terrain. L’écoute des équipes et des décideurs donne un point de départ commun à la mission.' },
      { title: 'Audit, cadrage & priorisation', body: 'Examiner les processus, les outils et les pratiques existantes. Définir ensemble les priorités, le périmètre de l’intervention et les critères de réussite.' },
      { title: 'Conception & feuille de route', body: 'Transformer les constats en solutions adaptées à votre contexte. Structurer une feuille de route avec des étapes, des responsabilités et des livrables clairement identifiés.' },
      { title: 'Déploiement opérationnel', body: 'Mettre en œuvre les solutions retenues, coordonner les intervenants et accompagner leur intégration aux opérations. Ajuster le déploiement aux réalités du terrain.' },
      { title: 'Formation & transfert de compétences', body: 'Préparer les équipes aux nouveaux outils et aux nouvelles pratiques. Documenter les usages et transmettre les compétences nécessaires pour favoriser une autonomie durable.' },
      { title: 'Suivi & amélioration continue', body: 'Observer les usages, suivre les indicateurs définis avec vous et identifier les ajustements utiles. Faire évoluer les dispositifs au rythme des besoins de votre organisation.' },
    ],
    projectsIntro: {
      eyebrow: 'Exemples de missions',
      title: 'Imaginer ce que nous pouvons construire.',
      description: 'Ces scénarios illustratifs présentent des types de missions adaptés aux secteurs que nous accompagnons. Ils ne constituent pas des références clients ni des réalisations revendiquées.',
    },
    projects: [
      {
        id: 'connected-administration',
        title: 'Une administration connectée',
        sector: 'Institutions publiques',
        context: 'Une administration souhaite simplifier le traitement de ses dossiers et mieux partager l’information entre ses services.',
        support: 'Une mission pourrait associer audit des processus, gestion électronique des documents et accompagnement des équipes pour faciliter la coordination au quotidien.',
        deliverables: ['Cartographie des processus', 'Feuille de route de digitalisation', 'Dispositif de gestion documentaire', 'Formation des utilisateurs'],
        image: '/images/architecture.jpg',
        imageAlt: 'Façade d’un bâtiment contemporain illustrant le secteur institutionnel.',
      },
      {
        id: 'institutional-brand',
        title: 'Une marque institutionnelle cohérente',
        sector: 'Communication & image de marque',
        context: 'Une organisation souhaite clarifier son positionnement et harmoniser son expression sur ses supports institutionnels et digitaux.',
        support: 'Un accompagnement pourrait relier stratégie de marque, identité visuelle et communication digitale pour construire une présence plus lisible et cohérente.',
        deliverables: ['Plateforme de marque', 'Charte graphique', 'Stratégie de communication', 'Ligne éditoriale digitale'],
        image: '/images/collaboration.jpg',
        imageAlt: 'Réunion de travail illustrant la conception collective d’une stratégie de communication.',
      },
      {
        id: 'sme-digitalization',
        title: 'Une PME mieux pilotée',
        sector: 'PME & PMI',
        context: 'Une entreprise en développement souhaite relier ses outils, réduire les ressaisies et disposer d’une vision plus claire de ses opérations.',
        support: 'La mission pourrait combiner cadrage des besoins, intégration ERP ou CRM et développement d’une application métier adaptée à ses processus.',
        deliverables: ['Diagnostic des besoins métiers', 'Plan d’intégration ERP ou CRM', 'Application et tableaux de bord', 'Accompagnement des équipes'],
        image: '/images/workspace.jpg',
        imageAlt: 'Espace de travail contemporain illustrant la modernisation des opérations d’une entreprise.',
      },
      {
        id: 'security-continuity',
        title: 'Sécurité & continuité numériques',
        sector: 'Systèmes d’information',
        context: 'Une organisation souhaite mieux maîtriser ses risques numériques et préparer la continuité de ses activités en cas d’incident.',
        support: 'Un accompagnement pourrait associer diagnostic de sécurité, structuration du réseau et préparation d’un dispositif de sauvegarde et de reprise.',
        deliverables: ['Diagnostic de sécurité', 'Préconisations d’infrastructure', 'Plan de continuité et de reprise', 'Sensibilisation des équipes'],
        image: '/images/infrastructure.jpg',
        imageAlt: 'Baies de serveurs illustrant les infrastructures et la continuité des systèmes d’information.',
      },
      {
        id: 'governance-training',
        title: 'Une gouvernance portée par les équipes',
        sector: 'Formation & conformité',
        context: 'Une structure souhaite clarifier ses procédures, développer les compétences numériques de ses équipes et préparer une démarche de conformité.',
        support: 'La mission pourrait réunir documentation des pratiques, formation aux outils digitaux et accompagnement à la préparation d’évaluations ou d’audits.',
        deliverables: ['Manuel de procédures', 'Parcours de formation', 'Guide de gouvernance', 'Feuille de route de conformité'],
        image: '/images/team.jpg',
        imageAlt: 'Professionnels en séance collaborative illustrant le partage de compétences.',
      },
      {
        id: 'impact-platform',
        title: 'Une plateforme au service de l’impact',
        sector: 'Éducation & inclusion numérique',
        context: 'Un porteur de projet souhaite faciliter l’accès à des ressources éducatives ou à des services d’accompagnement grâce au numérique.',
        support: 'Un accompagnement pourrait associer étude de faisabilité, conception d’une plateforme et structuration du projet pour préparer son développement et sa recherche de financement.',
        deliverables: ['Étude de faisabilité', 'Conception de la plateforme', 'Plan de développement', 'Dossier de financement'],
        image: '/images/city.jpg',
        imageAlt: 'Paysage urbain illustrant les territoires et les initiatives à impact.',
      },
    ],
    contactIntro: {
      eyebrow: 'Parlons de votre projet',
      title: 'Votre prochaine étape commence par un échange.',
      description: 'Vous souhaitez renforcer votre image, structurer votre communication ou moderniser vos systèmes ? Partagez vos priorités avec nous. Nous vous accompagnons avec clarté, confidentialité et méthode.',
    },
    footer: {
      description: 'Nous accompagnons les organisations qui veulent renforcer leur image, moderniser leurs processus et déployer des solutions digitales sécurisées et durables.',
      expertise: 'Communication stratégique · Communication digitale · Transformation digitale · Systèmes d’information · Conformité · Projets à impact',
    },
  },
  en: {
    brand: 'Imperial Digitale',
    location: 'Yaoundé, Cameroon',
    availability: 'By appointment, on-site or remote',
    nav: {
      home: 'Home',
      about: 'About',
      services: 'Services',
      industries: 'Industries',
      approach: 'Our Approach',
      projects: 'Projects',
      contact: 'Contact',
    },
    meta: 'Imperial Digitale is a Cameroon-based consulting firm specialized in strategic communication, digital transformation, information systems, cybersecurity, ISO compliance, and impact project support.',
    hero: {
      eyebrow: 'Strategy · Technology · Impact',
      title: 'Imperial Digitale',
      description: 'A consulting firm specializing in digital transformation, information systems, and strategic communication.',
      slides: [
        { label: 'A vision taking shape', alt: 'Contemporary architecture in a business district, with clean lines and natural light.' },
        { label: 'Opening new perspectives', alt: 'Glass façade of an office building illuminated at night.' },
        { label: 'Foundations for tomorrow', alt: 'Digital infrastructure with server racks inside a data center.' },
      ],
    },
    home: {
      introLabel: 'Transformation with purpose',
      introTitle: 'Turning your vision into meaningful change.',
      introBody: 'We support organizations in digitalizing and automating their operations, implementing high-performance information systems, designing and optimizing business applications, and deploying strategic technology solutions.',
      context: [
        'African institutions and businesses hold enormous potential. Yet manual processes, disconnected systems, and fragmented information can still stand in the way of their development.',
        'Imperial Digitale connects strategy, communication, technology, and execution to strengthen performance, improve decision-making, and accelerate organizational transformation.',
        'We support public institutions, private companies, SMEs and industrial businesses, local governments, and impact initiatives in modernizing their operations and strengthening their brand positioning.',
      ],
      benefitsTitle: 'Clear ambitions. Meaningful outcomes to work towards.',
      benefits: [
        'A stronger and more consistent brand image',
        'More efficient and better-managed processes',
        'Digital tools aligned with real business needs',
        'Better risk control and a stronger security posture',
        'More capable teams, better prepared for change',
        'More visible, credible, and fundable projects',
      ],
      whyTitle: 'A complete perspective. Disciplined execution.',
      why: [
        { title: 'Strategic vision', body: 'We design solutions aligned with your positioning, performance, and growth priorities. Every tool serves a clear ambition.' },
        { title: 'Disciplined execution', body: 'We support you from diagnosis to deployment through a structured, practical, and results-driven approach.' },
        { title: 'Cross-functional expertise', body: 'Communication, branding, digital, information systems, cybersecurity, compliance, and project support: we bring complementary capabilities together around one mission.' },
        { title: 'Local grounding, international standards', body: 'We understand African realities while integrating the quality, governance, and performance standards expected internationally.' },
      ],
      closingTitle: 'Give your organization a stronger digital future.',
      closingBody: 'From your brand to your information systems, let’s build solutions tailored to your sector, your priorities, and your ambitions.',
    },
    about: {
      eyebrow: 'The firm',
      title: 'Expertise in service of your ambition.',
      intro: [
        'Imperial Digitale is a consulting and execution firm helping organizations address challenges related to visibility, governance, performance, and digital transformation.',
        'Our approach combines strategy, technology, branding, institutional communication, innovation, compliance, and operational support.',
        'We believe transformation is not only about tools. It requires a clear vision, structured processes, strong positioning, and disciplined execution.',
      ],
      teamTitle: 'Complementary perspectives. One shared ambition.',
      teamBody: [
        'Imperial Digitale relies on a multidisciplinary team of specialists in digital transformation, strategic communication, information systems, and project management.',
        'We bring together complementary expertise capable of designing, leading, and deploying solutions tailored to the needs of institutions, companies, and impact-driven initiatives.',
      ],
      founderName: 'Lara Loe',
      founderRole: 'Founder & Director',
      founderBio: [
        'An information systems engineer and project manager, Lara Loe has expertise in digital transformation, process modernization, and the structuring of technology solutions for public institutions and private organizations.',
        'She supports institutions and companies in implementing information systems, digitalizing operations, and managing high-impact digital projects.',
        'Through Imperial Digitale, she promotes a vision of a consulting firm capable of helping African organizations reach international standards of performance, governance, and innovation.',
      ],
      valuesTitle: 'What guides every engagement.',
      values: [
        'A strategic, technical, and execution-driven approach',
        'Cross-functional expertise in communication, digital, information systems, and compliance',
        'Tailored solutions for public institutions, private companies, and impact projects',
        'A strong focus on results, governance, and sustainability',
      ],
    },
    servicesIntro: {
      eyebrow: 'Our areas of expertise',
      title: 'From strategy to implementation.',
      description: 'Five complementary capabilities to strengthen your brand, modernize your operations, and deliver useful, secure, and sustainable solutions.',
    },
    services: [
      {
        id: 'strategic-communication',
        title: 'Strategic Communication & Brand Image',
        body: 'We design strong communication strategies that help organizations clarify their positioning, strengthen credibility, and protect their reputation.',
        items: [
          'Internal and external communication strategy',
          'Visual identity design: logos, brand guidelines, and slogans',
          'Branding, storytelling, and market positioning',
          'Press relations and institutional communication',
          'Crisis communication',
          'Professional and public event organization',
        ],
      },
      {
        id: 'digital-communication',
        title: 'Digital Communication & Reputation Management',
        body: 'We help brands, executives, and institutions build a strong, visible, and well-managed digital presence.',
        items: [
          'Digital strategy and editorial planning',
          'Community management and social media moderation',
          'Content creation: visuals, videos, copy, and reels',
          'Personal branding for executives and experts',
          'Online reputation management',
          'Crisis response strategy for digital channels',
        ],
      },
      {
        id: 'digital-transformation',
        title: 'Digital Transformation & Information Systems',
        body: 'We support organizations in auditing, designing, deploying, and securing their digital systems.',
        items: [
          'Digital audit and digital maturity assessment',
          'Process mapping and business process reengineering',
          'Website, platform, and business application development',
          'Design and development of custom business applications',
          'Optimization, modernization, and performance improvement of existing applications',
          'ERP, CRM, document management, and collaboration tools integration',
          'Client-side project advisory, project framing, and digital project deployment',
          'Cybersecurity, business continuity planning, and disaster recovery sites',
          'Network infrastructure deployment: LAN, VPN, fiber, and routers',
          'IP telephony and virtual PBX systems',
          'Secure business internet solutions supply and installation',
        ],
      },
      {
        id: 'training-compliance',
        title: 'Training, Compliance & Advisory Support',
        body: 'We strengthen teams and support organizations in compliance, governance, and continuous improvement.',
        items: [
          'Training in digital tools, office productivity, cybersecurity, networking, and AI',
          'Digital coaching for executives, managers, and local governments',
          'Development of procedure manuals, governance guides, and protocols',
          'Compliance support for ISO 9001, ISO 27001, and ISO 14001',
          'Awareness programs on digital culture and ethical governance',
          'Support for certification, evaluation, and external audits',
        ],
      },
      {
        id: 'impact-projects',
        title: 'Business Support & Impact Projects',
        body: 'We help businesses, entrepreneurs, and institutions structure initiatives, secure growth, and design projects with strong social or economic value.',
        items: [
          'Support for the creation or transformation of SMEs and industrial businesses',
          'Advice on business models, branding, visibility, and digitalization',
          'Funding support: investment files, fundraising, grants, and public-private partnerships',
          'Feasibility studies and development plans',
          'Design of digital platforms for education, health, entrepreneurship, and social impact',
          'Management of impact projects: smart cities, mobility, digital inclusion, and territorial innovation',
        ],
      },
    ],
    industriesIntro: {
      eyebrow: 'Industries we serve',
      title: 'Your context sets the direction.',
      description: 'Every organization has its own priorities, constraints, and pace. We adapt our support to the realities of your sector, across Africa and internationally.',
    },
    industries: [
      { id: 'public-institutions', title: 'Public Institutions & Local Governments', body: 'Modernize services, structure information, and strengthen institutional communication in support of more effective governance.', serviceIds: ['digital-transformation', 'strategic-communication', 'training-compliance'] },
      { id: 'private-companies', title: 'Private Companies & Organizations in Transformation', body: 'Align brand positioning, information systems, and processes to support organizational change and manage development with greater clarity.', serviceIds: ['digital-transformation', 'strategic-communication', 'training-compliance'] },
      { id: 'smes', title: 'SMEs & Industrial Businesses', body: 'Structure operations, improve visibility, and select digital tools suited to the organization’s needs and resources.', serviceIds: ['impact-projects', 'digital-transformation', 'digital-communication'] },
      { id: 'health-social', title: 'Health & Social Impact Projects', body: 'Design useful platforms, organize processes, and support initiatives whose value is measured by the services they provide to people.', serviceIds: ['impact-projects', 'digital-transformation', 'training-compliance'] },
      { id: 'education', title: 'Education & Training', body: 'Build skills, support digital adoption, and design digital solutions that serve learning and knowledge sharing.', serviceIds: ['training-compliance', 'digital-transformation', 'impact-projects'] },
      { id: 'mobility', title: 'Logistics, Mobility & Smart Cities', body: 'Frame territorial projects, connect systems, and use digital tools to support coordination and decision-making.', serviceIds: ['impact-projects', 'digital-transformation', 'strategic-communication'] },
      { id: 'media', title: 'Media, Communication & Executive Branding', body: 'Clarify positioning, build a consistent digital presence, and help leaders manage their public image.', serviceIds: ['strategic-communication', 'digital-communication'] },
    ],
    approachIntro: {
      eyebrow: 'Our approach',
      title: 'A clear method, at every stage.',
      description: 'From the first conversation to continuous improvement, every engagement is designed with sustainability, knowledge transfer, governance, and measurable impact in mind.',
    },
    steps: [
      { title: 'Needs Assessment & Discovery', body: 'Understand your organization, your objectives, and the challenges faced on the ground. Listening to teams and decision-makers establishes a shared starting point.' },
      { title: 'Audit, Framing & Prioritization', body: 'Examine existing processes, tools, and practices. Define priorities, the scope of the engagement, and success criteria together.' },
      { title: 'Solution Design & Roadmap', body: 'Turn findings into solutions suited to your context. Build a roadmap with clearly identified stages, responsibilities, and deliverables.' },
      { title: 'Operational Deployment', body: 'Implement the agreed solutions, coordinate stakeholders, and support integration into day-to-day operations. Adapt delivery to practical realities.' },
      { title: 'Training & Knowledge Transfer', body: 'Prepare teams for new tools and ways of working. Document practices and transfer the skills needed to support lasting autonomy.' },
      { title: 'Monitoring & Continuous Improvement', body: 'Observe adoption, monitor the indicators agreed with you, and identify useful adjustments. Help solutions evolve alongside your organization’s needs.' },
    ],
    projectsIntro: {
      eyebrow: 'Illustrative engagements',
      title: 'Imagine what we could build together.',
      description: 'These illustrative scenarios show the types of engagements relevant to the sectors we serve. They are not client references or claims of completed work.',
    },
    projects: [
      {
        id: 'connected-administration',
        title: 'A Connected Administration',
        sector: 'Public Institutions',
        context: 'A public administration wants to simplify case processing and improve information sharing between departments.',
        support: 'An engagement could combine process assessment, digital document management, and team support to make everyday coordination easier.',
        deliverables: ['Process mapping', 'Digitalization roadmap', 'Document management framework', 'User training'],
        image: '/images/architecture.jpg',
        imageAlt: 'A contemporary building facade illustrating the institutional sector.',
      },
      {
        id: 'institutional-brand',
        title: 'A Consistent Institutional Brand',
        sector: 'Communication & Brand Image',
        context: 'An organization wants to clarify its positioning and bring consistency to its institutional and digital communications.',
        support: 'An engagement could connect brand strategy, visual identity, and digital communication to create a clearer and more consistent presence.',
        deliverables: ['Brand platform', 'Visual identity guidelines', 'Communication strategy', 'Digital editorial framework'],
        image: '/images/collaboration.jpg',
        imageAlt: 'A working meeting illustrating the collaborative development of a communication strategy.',
      },
      {
        id: 'sme-digitalization',
        title: 'Better-Managed Business Operations',
        sector: 'SMEs & Industrial Businesses',
        context: 'A growing business wants to connect its tools, reduce duplicate data entry, and gain a clearer view of its operations.',
        support: 'An engagement could combine requirements definition, ERP or CRM integration, and a business application tailored to existing processes.',
        deliverables: ['Business needs assessment', 'ERP or CRM integration plan', 'Application and dashboards', 'Team onboarding'],
        image: '/images/workspace.jpg',
        imageAlt: 'A contemporary workspace illustrating the modernization of business operations.',
      },
      {
        id: 'security-continuity',
        title: 'Digital Security & Continuity',
        sector: 'Information Systems',
        context: 'An organization wants to better manage digital risks and prepare for business continuity in the event of an incident.',
        support: 'An engagement could combine a security assessment, network design, and preparation of a backup and recovery framework.',
        deliverables: ['Security assessment', 'Infrastructure recommendations', 'Continuity and recovery plan', 'Team awareness sessions'],
        image: '/images/infrastructure.jpg',
        imageAlt: 'Server racks illustrating information systems infrastructure and continuity.',
      },
      {
        id: 'governance-training',
        title: 'Governance Strengthened by Teams',
        sector: 'Training & Compliance',
        context: 'An organization wants to clarify procedures, develop its teams’ digital skills, and prepare a compliance initiative.',
        support: 'An engagement could bring together process documentation, digital tools training, and support in preparing for assessments or audits.',
        deliverables: ['Procedure manual', 'Training program', 'Governance guide', 'Compliance roadmap'],
        image: '/images/team.jpg',
        imageAlt: 'Professionals in a collaborative session illustrating knowledge sharing.',
      },
      {
        id: 'impact-platform',
        title: 'A Platform for Impact',
        sector: 'Education & Digital Inclusion',
        context: 'A project leader wants to use digital technology to make educational resources or advisory services more accessible.',
        support: 'An engagement could combine a feasibility study, platform design, and project structuring to prepare for development and funding opportunities.',
        deliverables: ['Feasibility study', 'Platform design', 'Development plan', 'Funding application'],
        image: '/images/city.jpg',
        imageAlt: 'An urban landscape illustrating communities and impact-driven initiatives.',
      },
    ],
    contactIntro: {
      eyebrow: 'Let’s talk about your project',
      title: 'Your next step starts with a conversation.',
      description: 'Looking to strengthen your brand, structure your communication, or modernize your systems? Share your priorities with us. We work with clarity, discretion, and a considered approach.',
    },
    footer: {
      description: 'We support organizations seeking to strengthen their brand, modernize operations, and deploy secure, sustainable digital solutions.',
      expertise: 'Strategic Communication · Digital Communication · Digital Transformation · Information Systems · Compliance · Impact Projects',
    },
  },
}
